version: "3.9"

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.10
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
    volumes:
      - weaviate_data:/var/lib/weaviate

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medical-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - weaviate

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medical-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  weaviate_data:
